

export const textoGrupos = [
    {
titulo: 'Hongos', 
text: "<a><p>Los hongos son un reino diferente a las plantas y animales. A pesar de compartir algunas características con las plantas, como la carencia de capacidad locomotora, se diferencian en una característica fundamental; no producen fotosíntesis, se alimentan por absorción de nutrientes orgánicos, lo que los separa definitivamente de las plantas y los convierte en descomponed ores vitales para los ecosistemas.</p><p> La mayor parte del tiempo, se encuentran dentro del sustrato que los alimenta y se hacen visibles cuando producen una seta, el cuerpo frutoso que los caracteriza. Esta seta puede ser de diversas formas, tamaños y colores. Las más comunes son con forma de sombrero, globoso, de colmena, gelatinoso, coraloide, de disco y de estrella.</p><p> Hay diversas clases de hongos y se clasifican según el sustrato (suelo/ser vivo) del que viven. Entre ellos, restos vegetales, madera, pasto y estiércol. Los Hongos cumplen una función primordial sintetizando nutrientes de las raíces de los árboles, convirtiéndolos en material inorgánico esencial para los bosques y los todos los ecosistemas. Levaduras, mohos y setas son parte de este reino.</p></a> "
},
{ titulo: 'Anfibios y reptiles',
text: "<bb><p> Los anfibios y reptiles son animales vertebrados que en etapa embrionaria se desarrollan sin una membrana que los envuelva, como los peces. Regulan temperatura usando las condiciones de su entorno y por lo mismo, es común verlos inmóviles tomando sol. En casi todo lo demás, son diferentes.</p><p> Los <b>anfibios</b> atraviesan una transformación drástica para llegar a ser adultos, se llama metamorfosis. Cuando son larvas, respiran por branquias y son herbívoros; y al llegar a adultos, desarrollan pulmones y son carnívoros. Son ectotérmicos y viven parte de su vida en el agua y parte en la tierra. Son de muchos colores y la mayoría tiene aspecto vidrioso producto del agua. Ranas, sapos y salamandras son parte de este grupo.</p> Los <b>reptiles</b> son animales vertebrados en su mayoría cubiertos de escamas de queratina, una proteína que también encontramos en el polo de humanos y en las plumas de las aves. Son carnívoros, respiran usando pulmones y en su mayoría terrestres, pero también se han adaptado a desarrollar parte de su vida en el agua, como algunas tortugas, lagartos y serpientes. Tortugas, lagartos, lagartijas, camaleones, iguanas y serpientes, son reptiles y aunque la mayoría son de tonos verdosos, pueden ser de casi todos lo colores que conocemos.</bb> "
},{
titulo: 'Mamíferos',
text: "<c><p>Son animales vertebrados, de sangre caliente, es decir que regulan temperatura de manera autónoma y que poseen glándulas mamarias para producir leche y alimentar a sus crías. Los humanos somos mamíferos y somos el único grupo de animales que luego de la fecundación, la cría se desarrollo completamente dentro del cuerpo de la hembra, contenida por una estructura que le garantiza el flujo de oxígeno y alimento que necesita para alcanzar su desarrollo y nacer.</p><p> Los mamíferos son muy diversos, pueden verse y comportarse de maneras muy diferentes y ser muy difíciles de comparar unos de otros o incluso identificar cercanía entre ellos. <b>Son el único grupo de animales con pelo, o algún tipo de pelo, incluso en su etapa embrionaria y con pabellón auricular, o sea, “orejas”,</b> (con excepción de ballenas y delfines). Pueden ser herbívoros, carnívoros o ambos.</p><p>  Viven en la tierra, en el agua y en el aire. En la tierra suelen tener cuatro patas y en el mar se caracterizan por un notable desarrollo cerebral y/o social.</p><p> Ballenas, delfines, focas, marsupiales, primates, elefantes, perros, caballos, osos, zorros, lobos, felinos, mustélidos, roedores, camélidos, murciélagos, entre otros, son mamíferos. </p></c> "
}, {
titulo:  'Aves',
text: "<d><p>Las aves son animales vertebrados, que regulan temperatura de manera autónoma que caminan, saltan y se sostienen sólo sobre sus extremidades inferiores, es decir, las “piernas”. Esto porque sus extremidades superiores, los “brazos” son en realidad alas. Esta adaptación evolutiva los convierte en el gran grupo de vertebrados que puede volar. (Aunque existen las aves que no vuelan, como los pingüinos).</p><p> Tienen el cuerpo cubierto de plumas y un pico (boca) sin dientes que adquiere muy variadas formas y tamaños dependiendo de la forma en que lo usen para alimentarse. La gran mayoría pueden volar, incluso atravesar continentes, pero existen aves que no pueden volar como el ñandú, la avestruz y los pingüinos, que han adaptado sus alas para nadar.</p> Se reproducen depositando huevos, los cuales eclosionan produciendo una cría, por lo general calva y dependiente por un tiempo.</p></d>"
},{
titulo: 'Plantas y algas',
text: "<e><p> Este ícono agrupa a todas las especies que sostienen la vida terrestre, porque <b> son los únicos seres vivos capaces de producir su propio alimento utilizando la energía del sol, este proceso se llama fotosíntesis.</b> Las plantas y algas no poseen capacidad locomotora, es decir, no se desplazan autónomamente porque viven ancladas a la tierra, al fondo marino, a rocas o a otros seres vivos, a través de las raíces.</p><p> Algunos de <b> los órganos de las plantas son la raíz, el tallo (o tronco) y las hojas </b>, también pueden producir flores y frutos, los que usan para reproducirse. Árboles, arbustos, enredaderas, rastreras, hierbas, pastos, cactus, suculentas y plantas con flores son plantas.</p> <p> Las algas son organismos con algunas características diferentes a las plantas, la más importante es que <b> las algas habitan en el agua </b> y es común que su color lo adquieran por la coloración de los nutrientes del medio acuático que habitan. Pueden ser verdes, rojas, pardas, anaranjadas o tendiendo al amarillo.</p></e>" }
,{
titulo:  'Invertebrados marinos' ,
text: "<f><p>Se entenderá como invertebrados marinos a los animales que no poseen columna vertebral, ni esqueleto articulado y desarrollan su vida en el agua. Aquí se incluyen insectos y arácnidos acuáticos.</p><p> Estos animales suelen desarrollar exoesqueleto o una concha, para proteger el cuerpos y órganos, los que muchas veces, son blandos y frágiles. Pueden vivir en agua salada, dulce y salobre y a diversa profundidad. Habitan en la costa, en roqueríos y en grandes profundidades.</p><p> Además de insectos y arácnidos con hábitos acuáticos, en este grupo se encuentran crustáceos, almejas, choritos, lapas, calamares, pulpos, caracoles, esponjas, medusas, corales, pólipos, estrellas y erizos de mar.</p><p> Pueden ser animales pequeños, como los caracoles o almejas, medir más de 12 metros como los pulpos o decenas de metros como los corales. Son animales que desarrollan tentáculos, tenazas como los cangrejos, o brazos como las estrellas de mar.</p><p> A muchos les resultan muy llamativos por sus colores y los efectos tornasolados que desarrollan. Rojos, anaranjados, lilas, purpura, verdes, amarillos, entre muchos otros, son parte de la gran gama de colores de los invertebrados marinos.</p></f> "
}, 
{
 titulo: 'Artrópodos terrestres', 
 text:"<g><p>Este icono inspirado en el escarabajo de Darwin, agrupa a los animales invertebrados terrestres que comúnmente llamamos insectos o arañas que viven en la tierra. Por lo general son animales pequeños o muy pequeños. Ambos son artrópodos y reciben su nombre por poseer patas articuladas. Son un grupo altamente numeroso de especies y la mayoría posee exoesqueleto.</p><p> Los insectos se caracterizan por tener tres pares de patas en su etapa adulta, antenas y dos pares de alas. Su cuerpo adulto se estructura en tres segmentos: cabeza, tórax y abdomen. En la cabeza se ubica la mandíbula, los ojos compuestos y las antenas, mientras que del tórax se originan las alas. En el caso de las abejas, su aguijón se ubica en la parte inferior del abdomen. La mayoría de los insectos se desarrolla a través de una metamorfosis y en algunos casos, por metamorfosis completa (cuatro transformaciones radicales), como las mariposas. Dependiendo de la etapa de desarrollo y la especie, desarrollan mandíbulas para cortar, masticar, chupar, picar, lamer o combinaciones de estas. Las mandíbulas de los insectos son bastante específicos a lo que comen. Las hormigas, abejas, libélulas, saltamontes, moscar, pulgas, mariposas, escarabajos, cigarras, entre otros, son insectos.</p><p>  Las arañas o arácnidos tienen cuatro pares de patas, no tienen antenas y se articulan en dos secciones corporales: el cefalotorax y el abdomen. Desde el cefalotorax, aparecen apéndices. A diferencia de los insectos, las arañas no desarrollan ojos compuestos sino uno o más pares de ojos simples. Forman parte de este grupo las arañas, los escorpiones, garrapatas y ácaros, entre los más conocidos.</p></g>  "
}, {
 titulo:'Peces',
 text:"<hh><p>Le llamamos peces a casi todos los animales vertebrados adaptados para respirar bajo el agua. La mayoría usa branquias para captar el oxigeno del agua y como los anfibios y reptiles, regulan temperatura usando el entorno. La mayoría no posee extremidades, sino apéndices en forma de aletas, que les permiten nadar.</p><p> Los peces, son en realidad tres grupos de animales diferentes; los peces sin mandíbula o ciclóstomos como las anguilas babosas; los peces con mandíbula y esqueleto de cartílago, llamados condrictios, a este grupo pertenecen los tiburones, las manta rayas y los pejegallos. Y un tercer grupo con esqueleto y mandíbula de hueso, los osteoictios a los cuales pertenecen la mayor parte de los peces que conocemos. En este último grupo están las merluzas, congrios, lenguados, salmones, jureles, corvinas, entre otros.</p><p> Los osteoictios, peces de esqueleto de hueso, habitan en todos los ambientes y entre ellos se encuentran los únicos vertebrados capaces de producir luz y las únicas hembras capaces de reproducirse sin un macho.</p><p> Los peces pueden vivir cerca de la superficie, elevarse de ella como un ave y habitar las zonas más profundas del océano. Se reproducen depositando huevos y son de variadas formas, tamaños y colores. Pueden habitar en agua dulce, salada o salobre.</p></hh> "
}
];

